name: Testing - Reusable Workflow

on: 
  workflow_call:  # 다른 워크플로우에서 호출할 수 있도록 설정

inputs:  # ingress-url 입력 정의
  ingress-url:
    description: Provide the Ingress URL
    required: true
    type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run integration test
        env:
          URL: '${{ inputs.ingress-url }}'  # ingress-url 입력을 사용하여 URL 설정
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
